on:
  pull_request_target:
    types:
      - closed
name: CI/CD
jobs:
  release-please:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2.33.0
        id: release
        with:
          command: github-release
          token: ${{secrets.NODE_AUTH_TOKEN_GLOBAL}}
          package-name: webile,
          release-type: node
